.\" V7/x86 source code: see www.nordier.com/v7x86 for details.
.\" Copyright (c) 2006 Robert Nordier.  All rights reserved.
.TH CHROOT 1 
.SH NAME
chroot  \-  change root directory
.SH SYNOPSIS
.B chroot
path command ...
.SH DESCRIPTION
.I Chroot
changes its current and root directories to
.I path
and then executes
.I command
with any supplied arguments.
