hd0:
	/etc/mknod hd0 b 0 2
	/etc/mknod hd0a b 0 56
	/etc/mknod swap b 0 57
	/etc/mknod hd0c b 0 58
	/etc/mknod hd0e b 0 60
	/etc/mknod rhd0 c 4 2
	/etc/mknod rhd0a c 4 56
	/etc/mknod rhd0c c 4 58
	/etc/mknod rhd0e c 4 60
	chmod go-w hd0 hd0a swap hd0c hd0e rhd0 rhd0a rhd0c rhd0e

hd1:
	/etc/mknod hd1 b 0 66
	/etc/mknod hd1a b 0 120
	/etc/mknod swap b 0 121
	/etc/mknod hd1c b 0 122
	/etc/mknod hd1e b 0 124
	/etc/mknod rhd1 c 4 66
	/etc/mknod rhd1a c 4 120
	/etc/mknod rhd1c c 4 122
	/etc/mknod rhd1e c 4 124
	chmod go-w hd1 hd1a swap hd1c hd1e rhd1 rhd1a rhd1c rhd1e
